export const ALL_COUNTRIES = [
  { name: 'Afghanistan', code: 'AF', flag: '????' },
  { name: 'Afrique du Sud', code: 'ZA', flag: '????' },
  { name: 'Albanie', code: 'AL', flag: '????' },
  { name: 'Alg?rie', code: 'DZ', flag: '????' },
  { name: 'Allemagne', code: 'DE', flag: '????' },
  { name: 'Andorre', code: 'AD', flag: '????' },
  { name: 'Angola', code: 'AO', flag: '????' },
  { name: 'Antigua-et-Barbuda', code: 'AG', flag: '????' },
  { name: 'Arabie Saoudite', code: 'SA', flag: '????' },
  { name: 'Argentine', code: 'AR', flag: '????' },
  { name: 'Arm?nie', code: 'AM', flag: '????' },
  { name: 'Australie', code: 'AU', flag: '????' },
  { name: 'Autriche', code: 'AT', flag: '????' },
  { name: 'Azerba?djan', code: 'AZ', flag: '????' },
  { name: 'Bahamas', code: 'BS', flag: '????' },
  { name: 'Bahre?n', code: 'BH', flag: '????' },
  { name: 'Bangladesh', code: 'BD', flag: '????' },
  { name: 'Barbade', code: 'BB', flag: '????' },
  { name: 'Belgique', code: 'BE', flag: '????' },
  { name: 'Belize', code: 'BZ', flag: '????' },
  { name: 'B?nin', code: 'BJ', flag: '????' },
  { name: 'Bhoutan', code: 'BT', flag: '????' },
  { name: 'Bi?lorussie', code: 'BY', flag: '????' },
  { name: 'Birmanie', code: 'MM', flag: '????' },
  { name: 'Bolivie', code: 'BO', flag: '????' },
  { name: 'Bosnie-Herz?govine', code: 'BA', flag: '????' },
  { name: 'Botswana', code: 'BW', flag: '????' },
  { name: 'Br?sil', code: 'BR', flag: '????' },
  { name: 'Brunei', code: 'BN', flag: '????' },
  { name: 'Bulgarie', code: 'BG', flag: '????' },
  { name: 'Burkina Faso', code: 'BF', flag: '????' },
  { name: 'Burundi', code: 'BI', flag: '????' },
  { name: 'Cambodge', code: 'KH', flag: '????' },
  { name: 'Cameroun', code: 'CM', flag: '????' },
  { name: 'Canada', code: 'CA', flag: '????' },
  { name: 'Cap-Vert', code: 'CV', flag: '????' },
  { name: 'Chili', code: 'CL', flag: '????' },
  { name: 'Chine', code: 'CN', flag: '????' },
  { name: 'Chypre', code: 'CY', flag: '????' },
  { name: 'Colombie', code: 'CO', flag: '????' },
  { name: 'Comores', code: 'KM', flag: '????' },
  { name: 'Congo-Brazzaville', code: 'CG', flag: '????' },
  { name: 'Congo-Kinshasa', code: 'CD', flag: '????' },
  { name: 'Cor?e du Nord', code: 'KP', flag: '????' },
  { name: 'Cor?e du Sud', code: 'KR', flag: '????' },
  { name: 'Costa Rica', code: 'CR', flag: '????' },
  { name: "Cote d'Ivoire", code: 'CI', flag: 'CI' },
  { name: 'Croatie', code: 'HR', flag: '????' },
  { name: 'Cuba', code: 'CU', flag: '????' },
  { name: 'Danemark', code: 'DK', flag: '????' },
  { name: 'Djibouti', code: 'DJ', flag: '????' },
  { name: 'Dominique', code: 'DM', flag: '????' },
  { name: '?gypte', code: 'EG', flag: '????' },
  { name: '?mirats Arabes Unis', code: 'AE', flag: '????' },
  { name: '?quateur', code: 'EC', flag: '????' },
  { name: '?rythr?e', code: 'ER', flag: '????' },
  { name: 'Espagne', code: 'ES', flag: '????' },
  { name: 'Estonie', code: 'EE', flag: '????' },
  { name: 'Eswatini', code: 'SZ', flag: '????' },
  { name: '?tats-Unis', code: 'US', flag: '????' },
  { name: '?thiopie', code: 'ET', flag: '????' },
  { name: 'Fidji', code: 'FJ', flag: '????' },
  { name: 'Finlande', code: 'FI', flag: '????' },
  { name: 'France', code: 'FR', flag: '????' },
  { name: 'Gabon', code: 'GA', flag: '????' },
  { name: 'Gambie', code: 'GM', flag: '????' },
  { name: 'G?orgie', code: 'GE', flag: '????' },
  { name: 'Ghana', code: 'GH', flag: '????' },
  { name: 'Gr?ce', code: 'GR', flag: '????' },
  { name: 'Grenade', code: 'GD', flag: '????' },
  { name: 'Guatemala', code: 'GT', flag: '????' },
  { name: 'Guin?e', code: 'GN', flag: '????' },
  { name: 'Guin?e ?quatoriale', code: 'GQ', flag: '????' },
  { name: 'Guin?e-Bissau', code: 'GW', flag: '????' },
  { name: 'Guyana', code: 'GY', flag: '????' },
  { name: 'Ha?ti', code: 'HT', flag: '????' },
  { name: 'Honduras', code: 'HN', flag: '????' },
  { name: 'Hongrie', code: 'HU', flag: '????' },
  { name: 'Inde', code: 'IN', flag: '????' },
  { name: 'Indon?sie', code: 'ID', flag: '????' },
  { name: 'Irak', code: 'IQ', flag: '????' },
  { name: 'Iran', code: 'IR', flag: '????' },
  { name: 'Irlande', code: 'IE', flag: '????' },
  { name: 'Islande', code: 'IS', flag: '????' },
  { name: 'Isra?l', code: 'IL', flag: '????' },
  { name: 'Italie', code: 'IT', flag: '????' },
  { name: 'Jama?que', code: 'JM', flag: '????' },
  { name: 'Japon', code: 'JP', flag: '????' },
  { name: 'Jordanie', code: 'JO', flag: '????' },
  { name: 'Kazakhstan', code: 'KZ', flag: '????' },
  { name: 'Kenya', code: 'KE', flag: '????' },
  { name: 'Kirghizistan', code: 'KG', flag: '????' },
  { name: 'Kiribati', code: 'KI', flag: '????' },
  { name: 'Kowe?t', code: 'KW', flag: '????' },
  { name: 'Laos', code: 'LA', flag: '????' },
  { name: 'Lesotho', code: 'LS', flag: '????' },
  { name: 'Lettonie', code: 'LV', flag: '????' },
  { name: 'Liban', code: 'LB', flag: '????' },
  { name: 'Liberia', code: 'LR', flag: '????' },
  { name: 'Libye', code: 'LY', flag: '????' },
  { name: 'Liechtenstein', code: 'LI', flag: '????' },
  { name: 'Lituanie', code: 'LT', flag: '????' },
  { name: 'Luxembourg', code: 'LU', flag: '????' },
  { name: 'Mac?doine du Nord', code: 'MK', flag: '????' },
  { name: 'Madagascar', code: 'MG', flag: '????' },
  { name: 'Malaisie', code: 'MY', flag: '????' },
  { name: 'Malawi', code: 'MW', flag: '????' },
  { name: 'Maldives', code: 'MV', flag: '????' },
  { name: 'Mali', code: 'ML', flag: '????' },
  { name: 'Malte', code: 'MT', flag: '????' },
  { name: 'Maroc', code: 'MA', flag: '????' },
  { name: 'Maurice', code: 'MU', flag: '????' },
  { name: 'Mauritanie', code: 'MR', flag: '????' },
  { name: 'Mexique', code: 'MX', flag: '????' },
  { name: 'Micron?sie', code: 'FM', flag: '????' },
  { name: 'Moldavie', code: 'MD', flag: '????' },
  { name: 'Monaco', code: 'MC', flag: '????' },
  { name: 'Mongolie', code: 'MN', flag: '????' },
  { name: 'Mont?n?gro', code: 'ME', flag: '????' },
  { name: 'Mozambique', code: 'MZ', flag: '????' },
  { name: 'Namibie', code: 'NA', flag: '????' },
  { name: 'Nauru', code: 'NR', flag: '????' },
  { name: 'N?pal', code: 'NP', flag: '????' },
  { name: 'Nicaragua', code: 'NI', flag: '????' },
  { name: 'Niger', code: 'NE', flag: '????' },
  { name: 'Nigeria', code: 'NG', flag: '????' },
  { name: 'Norv?ge', code: 'NO', flag: '????' },
  { name: 'Nouvelle-Z?lande', code: 'NZ', flag: '????' },
  { name: 'Oman', code: 'OM', flag: '????' },
  { name: 'Ouganda', code: 'UG', flag: '????' },
  { name: 'Ouzb?kistan', code: 'UZ', flag: '????' },
  { name: 'Pakistan', code: 'PK', flag: '????' },
  { name: 'Palaos', code: 'PW', flag: '????' },
  { name: 'Panama', code: 'PA', flag: '????' },
  { name: 'Papouasie-Nouvelle-Guin?e', code: 'PG', flag: '????' },
  { name: 'Paraguay', code: 'PY', flag: '????' },
  { name: 'Pays-Bas', code: 'NL', flag: '????' },
  { name: 'P?rou', code: 'PE', flag: '????' },
  { name: 'Philippines', code: 'PH', flag: '????' },
  { name: 'Pologne', code: 'PL', flag: '????' },
  { name: 'Portugal', code: 'PT', flag: '????' },
  { name: 'Qatar', code: 'QA', flag: '????' },
  { name: 'R?publique centrafricaine', code: 'CF', flag: '????' },
  { name: 'R?publique dominicaine', code: 'DO', flag: '????' },
  { name: 'Roumanie', code: 'RO', flag: '????' },
  { name: 'Royaume-Uni', code: 'GB', flag: '????' },
  { name: 'Russie', code: 'RU', flag: '????' },
  { name: 'Rwanda', code: 'RW', flag: '????' },
  { name: 'Saint-Kitts-et-Nevis', code: 'KN', flag: '????' },
  { name: 'Saint-Marin', code: 'SM', flag: '????' },
  { name: 'Saint-Vincent-et-les-Grenadines', code: 'VC', flag: '????' },
  { name: 'Sainte-Lucie', code: 'LC', flag: '????' },
  { name: 'Salvador', code: 'SV', flag: '????' },
  { name: 'Samoa', code: 'WS', flag: '????' },
  { name: 'S?o Tom?-et-Pr?ncipe', code: 'ST', flag: '????' },
  { name: 'S?n?gal', code: 'SN', flag: '????' },
  { name: 'Serbie', code: 'RS', flag: '????' },
  { name: 'Seychelles', code: 'SC', flag: '????' },
  { name: 'Sierra Leone', code: 'SL', flag: '????' },
  { name: 'Singapour', code: 'SG', flag: '????' },
  { name: 'Slovaquie', code: 'SK', flag: '????' },
  { name: 'Slov?nie', code: 'SI', flag: '????' },
  { name: 'Somalie', code: 'SO', flag: '????' },
  { name: 'Soudan', code: 'SD', flag: '????' },
  { name: 'Soudan du Sud', code: 'SS', flag: '????' },
  { name: 'Sri Lanka', code: 'LK', flag: '????' },
  { name: 'Su?de', code: 'SE', flag: '????' },
  { name: 'Suisse', code: 'CH', flag: '????' },
  { name: 'Suriname', code: 'SR', flag: '????' },
  { name: 'Syrie', code: 'SY', flag: '????' },
  { name: 'Tadjikistan', code: 'TJ', flag: '????' },
  { name: 'Tanzanie', code: 'TZ', flag: '????' },
  { name: 'Tchad', code: 'TD', flag: '????' },
  { name: 'Tch?quie', code: 'CZ', flag: '????' },
  { name: 'Tha?lande', code: 'TH', flag: '????' },
  { name: 'Timor oriental', code: 'TL', flag: '????' },
  { name: 'Togo', code: 'TG', flag: '????' },
  { name: 'Tonga', code: 'TO', flag: '????' },
  { name: 'Trinit?-et-Tobago', code: 'TT', flag: '????' },
  { name: 'Tunisie', code: 'TN', flag: '????' },
  { name: 'Turkm?nistan', code: 'TM', flag: '????' },
  { name: 'Turquie', code: 'TR', flag: '????' },
  { name: 'Tuvalu', code: 'TV', flag: '????' },
  { name: 'Ukraine', code: 'UA', flag: '????' },
  { name: 'Uruguay', code: 'UY', flag: '????' },
  { name: 'Vanuatu', code: 'VU', flag: '????' },
  { name: 'Vatican', code: 'VA', flag: '????' },
  { name: 'Venezuela', code: 'VE', flag: '????' },
  { name: 'Vi?t Nam', code: 'VN', flag: '????' },
  { name: 'Y?men', code: 'YE', flag: '????' },
  { name: 'Zambie', code: 'ZM', flag: '????' },
  { name: 'Zimbabwe', code: 'ZW', flag: '????' }
];
